# 공통 설정
spring:
  application:
    name: Beat-up
  profiles:
    default: pg-dev # 기본은 H2(기존 개발 방식 유지)
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000, expireAfterWrite=1h
  config:
    import: optional:file:.env[.properties]
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: Asia/Seoul


  server:
    port: 8080

# KOPIS API 설정
kopis:
  api:
    base-url: http://www.kopis.or.kr/openApi/restful
    service-key: ${KOPIS_SERVICE_KEY}
    timeout: 30000
    max-retry: 3
    delay-between-calls: 1000
    response-format: xml

# KAKAO API 설정
kakao:
  api:
    key: ${KAKAO_API_KEY}
    base-url: https://dapi.kakao.com
    timeout: 1500ms
    retry-count: 1
    max-connections: 50

logging:
  level:
    com.BeatUp.BackEnd.places.client: DEBUG

# JWT 설정 (공통)
auth:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: 60

# Swagger 설정 (공통)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs
    disable-swagger-default-url: false
    try-it-out-enabled: true

# firebase 인증 키
firebase:
  enabled: true
  service-account:
    key-path: ${FIREBASE_KEY_PATH}

---
# H2 프로필 (기존 개발 환경 유지)
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: false # H2에서는 Flyway 비활성화

---
# PostgreSQL 프로필(새로운 운영 환경)
spring:
  config:
    activate:
      on-profile: pg-dev
  datasource:
    url: jdbc:postgresql://localhost:5433/beatup
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration


kakao:
  api:
    key: ${KAKAO_API_KEY:your-api-key-here}
    base-url: https://dapi.key.com
    timeout: 1500ms
    retry-count: 1
    max-connections: 50

  logging:
    level:
      com.BeatUp.BackEnd.places.client: DEBUG

app:
  paging:
    default-size: 20
    max-size: 100
    min-size: 1
    default-sort-by: createdAt
    default-direction: DESC

# Redis 설정 추가
data:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
