apiVersion: v1
kind: ConfigMap
metadata:
  name: beatup-config
  namespace: beatup
data:
  application.yml: |
    spring:
      application:
        name: Beat-up
      profiles:
        active: production
      cache:
        type: redis
      server:
        port: 8080
      datasource:
        url: jdbc:postgresql://beatup-postgres:5432/beatup
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
      flyway:
        enabled: true
    data:
      redis:
        host: beatup-redis
        port: 6379
    kopis:
      api:
        base-url: http://www.kopis.or.kr/openApi/restful
    kakao:
      api:
        base-url: https://dapi.kakao.com
    springdoc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui.html