apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beatup-ingress
  namespace: beatup
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.beatup.com
      secretName: beatup-tls
  rules:
    - host: api.beatup.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: beatup-backend
                port:
                  number: 80