apiVersion: v1
kind: Secret
metadata:
  name: beatup-secrets
  namespace: beatup
type: Opaque
stringData:
  DB_USERNAME: beatup
  DB_PASSWORD: beatup1234
  JWT_SECRET: mySecretKeyForDevelopmentOnly1234567890123456789012345678901234567890abcdef
  KOPIS_SERVICE_KEY: 751675ec208b42ccac815d85d6071a4f
  KAKAO_API_KEY: 32c28576f4b4c1e52aeb004d9c46b587
  FIREBASE_KEY_PATH: firebase/beatup-7ca5d-firebase-adminsdk-fbsvc-c60582a84b.json
